FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir grpcio grpcio-tools

COPY file_service.proto grpc_server.py ./

RUN python -m grpc_tools.protoc --python_out=. --grpc_python_out=. -I. file_service.proto

EXPOSE 50051

CMD ["python", "grpc_server.py"]